### PR TITLE
Install list of packages

### PR DESCRIPTION
**Pull request by davecramer**
This works fine on rhel5, 

On suse this fails due to old root certs. May need to update the docker image we use for suse

### CODE REVIEW

**Comment by Eulerizeit** [comment]
What is happening with this PR? Could someone review it, and/or comment on it. I thought this story was in the backlog somewhere and I'm not clear where the work is being done.

**Comment by schubert** [comment]
@ictmalili bump

**Comment by paul-guo-** [comment]
This patch adds some R packages into the R/PLR packages. I think this seems to be not that necessary for an open source repo. This could be handled in separate repo.

**Comment by schubert** [comment]
@paul-guo- I'm not sure I follow - is this not augmenting the concourse build script to install the necessary packages for CI? It's common for CI scripts to include all steps needed to install dependencies (assuming the environment does not provide it). For a small project like PL/R a separate repo just for handling build dependencies seems like a lot of extra work and makes it harder for external contributors to replicate the test/CI environment because the details live somewhere else.

cc @pivotal-mike @yydzero @professor  - we should probably be consistent across PL/* and other repos like PostGIS in this regard.

**Pull request closed without merging**
